version: '3.8'
services:
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    environment:
      - PBF_URL=https://download.geofabrik.de/asia/cambodia-latest.osm.pbf
    ports:
      - "3000:8080"
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    restart: unless-stopped

volumes:
  nominatim-data: