version: "3.8"

services:
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    environment:
      PBF_URL: https://download.geofabrik.de/asia/cambodia-latest.osm.pbf
    ports:
      - "80:8080"
    # # Equivalent of `-it` in docker run
    # tty: true
    # stdin_open: true
    # restart: unless-stopped
    # Uncomment the volumes below if you want data to persist across restarts
    # (paths may vary by image version; consult image docs if needed)
    volumes:
        - nominatim-data:/var/lib/postgresql/16/main

volumes:
    nominatim-data:
